name: Portfolio
on:
  schedule: # Run every day
    - cron: '0 * * * *'
  workflow_dispatch: 
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pull in dev.to posts
      uses: gautamkrishnar/blog-post-workflow@main
        with:
        comment_tag_name: "Portfolio"
          feed_list: "https://github.com/TetianaTkachenko-qa"
